site_name: Fraytools unofficial documentation

theme:
  name: material
  features:
    - content.code.annotate 

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.snippets

nav:
  - Home: 'index.md'
  - Guides:
    - 'Getting Started':
      - 'Installation': 'guides/getting-started/installation.md'
      - 'Your first assist': 'guides/getting-started/your-first-assist.md'
      - 'Your first stage': 'guides/getting-started/your-first-stage.md'
      - 'How to contribute': 'guides/how-to-contribute.md'
  - About:
    - 'License': 'about/license.md'
    - 'Changelog': 'about/changelog.md'
